# Generated by Django 4.2.7 on 2025-10-30 08:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venue_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, help_text='Assignment date')),
                ('user', models.ForeignKey(help_text='Hall Admin user', limit_choices_to={'role': 'hall_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_venues', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(help_text='Assigned venue', on_delete=django.db.models.deletion.CASCADE, related_name='venue_admins', to='venue_management.venue')),
            ],
            options={
                'verbose_name': 'Venue Administrator',
                'verbose_name_plural': 'Venue Administrators',
                'db_table': 'venue_admins',
                'ordering': ['venue__name', 'user__first_name'],
                'unique_together': {('user', 'venue')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name/title of the event', max_length=200)),
                ('event_description', models.TextField(blank=True, help_text='Purpose/details of the event', null=True)),
                ('date', models.DateField(help_text='Booking date')),
                ('start_time', models.TimeField(help_text='Event start time')),
                ('end_time', models.TimeField(help_text='Event end time')),
                ('expected_attendees', models.IntegerField(help_text='Expected number of attendees', validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_number', models.CharField(help_text='Contact number for the event', max_length=20)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special needs/requirements', null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', help_text='Booking status', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation (if cancelled)', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Cancellation timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(help_text='Venue being booked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='venue_management.venue')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['venue', 'date'], name='bookings_venue_i_e2ce8c_idx'), models.Index(fields=['user'], name='bookings_user_id_fdc49e_idx'), models.Index(fields=['status'], name='bookings_status_51373b_idx'), models.Index(fields=['date'], name='bookings_date_438f98_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('venue', 'date', 'start_time', 'end_time'), name='unique_venue_datetime'),
        ),
    ]
