# Generated by Django 4.2.7 on 2025-11-05 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_system', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Requested booking date')),
                ('start_time', models.TimeField(help_text='Requested start time')),
                ('end_time', models.TimeField(help_text='Requested end time')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When user joined waitlist')),
                ('notified', models.BooleanField(default=False, help_text='Whether user has been notified of available slot')),
                ('notified_at', models.DateTimeField(blank=True, help_text='When user was notified', null=True)),
                ('claimed', models.BooleanField(default=False, help_text='Whether user claimed the slot')),
                ('claimed_at', models.DateTimeField(blank=True, help_text='When slot was claimed', null=True)),
                ('expired', models.BooleanField(default=False, help_text='Whether notification expired (15-min window passed)')),
                ('priority', models.IntegerField(default=0, help_text='Lower number = higher priority (0 = normal)')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'db_table': 'waitlist',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='auto_cancel_reason',
            field=models.CharField(blank=True, help_text='Reason for auto-cancellation', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='auto_cancelled',
            field=models.BooleanField(default=False, help_text='Whether booking was auto-cancelled by system'),
        ),
        migrations.AddField(
            model_name='booking',
            name='auto_cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when auto-cancelled', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Whether user has confirmed the booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when booking was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether 24-hour reminder has been sent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when reminder was sent', null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'status', 'reminder_sent'], name='bookings_date_35c2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'start_time', 'confirmed'], name='bookings_date_17f9df_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['venue', 'date', 'status'], name='bookings_venue_i_36f9e4_idx'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='user',
            field=models.ForeignKey(help_text='User waiting for this slot', on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='venue',
            field=models.ForeignKey(help_text='Venue for waitlist', on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='venue_management.venue'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['venue', 'date', 'start_time'], name='waitlist_venue_i_f43c31_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['user', 'claimed', 'expired'], name='waitlist_user_id_4a4ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['notified', 'expired', 'claimed'], name='waitlist_notifie_a6c045_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['priority', 'created_at'], name='waitlist_priorit_1ce8c4_idx'),
        ),
    ]
