# Generated by Django 4.2.7 on 2025-10-30 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Venue name (e.g., LRDC Hall)', max_length=100, unique=True)),
                ('location', models.CharField(help_text='Full location description', max_length=255)),
                ('building', models.CharField(help_text='Building name', max_length=100)),
                ('floor', models.CharField(help_text='Floor number/name', max_length=20)),
                ('capacity', models.IntegerField(help_text='Maximum person capacity', validators=[django.core.validators.MinValueValidator(1)])),
                ('facilities', models.JSONField(blank=True, default=list, help_text="Available facilities (e.g., ['Projector', 'AC', 'Audio System'])", null=True)),
                ('description', models.TextField(blank=True, help_text='Additional venue details', null=True)),
                ('photo_url', models.URLField(blank=True, help_text='URL/path to venue photo', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether venue is available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'db_table': 'venues',
                'ordering': ['name'],
            },
        ),
    ]
